#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class BinContents:
  NOISE = 0
  FM = 1
  QPSK = 2
  GMSK = 3

  _VALUES_TO_NAMES = {
    0: "NOISE",
    1: "FM",
    2: "QPSK",
    3: "GMSK",
  }

  _NAMES_TO_VALUES = {
    "NOISE": 0,
    "FM": 1,
    "QPSK": 2,
    "GMSK": 3,
  }

